model:
  layers: 8
  hidden_size: 512
  dim_feedforward: 2048
  heads: 8
  context_length: 1024
  vocab_size: 512

training:
  batch_size: 128
  learning_rate: 0.0002
  epochs: 30
  save_interval: 5
  genre: "all"
  track_type: "multi"

tokenizer:
  type: "REMI+"
  quantize_tempo: 12
  quantize_velocity: 8
